##--------------------------------------------## Primary db-------------------------------------------------------------------

spring.datasource.url=jdbc:mysql://localhost:3306/db_iemr
spring.datasource.username=root
spring.datasource.password=BizDev@24BB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##--------------------------------------------## Secondary db-------------------------------------------------------------------
secondary.datasource.url=jdbc:mysql://localhost:3306/db_identity
secondary.datasource.username=root
secondary.datasource.password=BizDev@24BB
secondary.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true